import { Translation } from 'primeng/api';

import {
  capitalizar,
  DIAS,
  DIAS_CORTOS,
  DIAS_MIN,
  MESES,
  MESES_CORTOS,
} from '../../shared/utils/meses-es';

/**
 * Traducción global de PrimeNG al español. Sin ella todos los calendarios
 * del sistema (p-calendar / p-datepicker) mostraban meses y días en inglés.
 * Se registra una vez en app.config.ts (providePrimeNG → translation).
 */
export const PRIMENG_ES: Translation = {
  dayNames: DIAS.map(capitalizar),
  dayNamesShort: DIAS_CORTOS.map(capitalizar),
  dayNamesMin: DIAS_MIN,
  monthNames: MESES.map(capitalizar),
  monthNamesShort: MESES_CORTOS.map(capitalizar),
  firstDayOfWeek: 1, // en Colombia la semana del calendario arranca el lunes
  dateFormat: 'dd/mm/yy',
  today: 'Hoy',
  clear: 'Limpiar',
  weekHeader: 'Sem',
  am: 'a. m.',
  pm: 'p. m.',
  chooseYear: 'Elegir año',
  chooseMonth: 'Elegir mes',
  chooseDate: 'Elegir fecha',
  prevDecade: 'Década anterior',
  nextDecade: 'Década siguiente',
  prevYear: 'Año anterior',
  nextYear: 'Año siguiente',
  prevMonth: 'Mes anterior',
  nextMonth: 'Mes siguiente',
  prevHour: 'Hora anterior',
  nextHour: 'Hora siguiente',
  prevMinute: 'Minuto anterior',
  nextMinute: 'Minuto siguiente',
  accept: 'Sí',
  reject: 'No',
  choose: 'Elegir',
  upload: 'Subir',
  cancel: 'Cancelar',
  emptyMessage: 'Sin resultados',
  emptyFilterMessage: 'Sin resultados',
  searchMessage: '{0} resultados disponibles',
  selectionMessage: '{0} elementos seleccionados',
  emptySelectionMessage: 'Ningún elemento seleccionado',
  emptySearchMessage: 'Sin resultados',
  startsWith: 'Empieza con',
  contains: 'Contiene',
  notContains: 'No contiene',
  endsWith: 'Termina con',
  equals: 'Igual a',
  notEquals: 'Distinto de',
  noFilter: 'Sin filtro',
  lt: 'Menor que',
  lte: 'Menor o igual que',
  gt: 'Mayor que',
  gte: 'Mayor o igual que',
  is: 'Es',
  isNot: 'No es',
  before: 'Antes',
  after: 'Después',
  dateIs: 'Fecha igual a',
  dateIsNot: 'Fecha distinta de',
  dateBefore: 'Fecha anterior a',
  dateAfter: 'Fecha posterior a',
  apply: 'Aplicar',
  matchAll: 'Coincidir todos',
  matchAny: 'Coincidir alguno',
  addRule: 'Agregar regla',
  removeRule: 'Quitar regla',
  passwordPrompt: 'Escriba una contraseña',
  weak: 'Débil',
  medium: 'Media',
  strong: 'Fuerte',
};
